# Generated by Django 4.0.4 on 2022-06-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_fundutilization_fablab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundutilization',
            name='prototypeGrant',
        ),
    ]
