# Generated by Django 4.0.4 on 2022-06-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_fundutilization_prototypegrant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funddisbursement',
            old_name='prototypeGrant',
            new_name='capitalAmount',
        ),
        migrations.RenameField(
            model_name='fundutilization',
            old_name='prototypeGrant',
            new_name='capitalAmount',
        ),
    ]
