# Generated by Django 4.0.4 on 2022-06-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_prototypegrant_funddisbursement_capitalamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funddisbursement',
            old_name='operationExpenditure',
            new_name='operatingAmount',
        ),
    ]
