# Generated by Django 4.0.4 on 2022-06-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_rename_operationexpenditure_funddisbursement_operatingamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funddisbursement',
            old_name='fabLab',
            new_name='fundAmount',
        ),
    ]
