# Generated by Django 4.0.4 on 2022-06-01 16:49

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_rename_fablab_funddisbursement_fundamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFundRaised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=50, verbose_name='Agency')),
                ('amount', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed', regex='^[0-9,]*$')], verbose_name='Amount')),
                ('updateOn', models.DateField(default=datetime.date.today)),
                ('financialYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.financialyear', verbose_name='Financial Year')),
                ('fundType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.fundingtype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.project')),
            ],
        ),
    ]
